# Generated by Django 3.0.7 on 2021-03-18 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfilemodel',
            name='some_field',
        ),
    ]
